import { Router, type IRouter } from "express";
import { HealthCheckResponse } from "@workspace/api-zod";
import { BUILD_FINGERPRINT } from "../lib/build-info.js";

const router: IRouter = Router();

router.get("/healthz", (_req, res) => {
  /*
   * The fingerprint rides in a header rather than the body: the body is
   * validated against HealthCheckResponse, which is generated by orval from
   * lib/api-spec/openapi.yaml, so adding a field there would mean changing the
   * published API contract to serve a local test script. A header carries the
   * same information without touching the contract.
   *
   * Development only. It exists for scripts/wait-for-api.sh, which never runs
   * against production, and there is no reason to advertise build identity on
   * an unauthenticated public endpoint.
   */
  if (process.env.NODE_ENV !== "production") {
    res.set("X-Build-Fingerprint", BUILD_FINGERPRINT);
  }

  const data = HealthCheckResponse.parse({ status: "ok" });
  res.json(data);
});

export default router;
