-- Generated by drizzle-kit, then edited once, before ever being applied, to add
-- IF NOT EXISTS to each statement. These three indexes were previously created
-- at boot by ensureChatTables() in artifacts/api-server/src/index.ts, which this
-- migration replaces. Every database that has ever started the server therefore
-- already carries them, under these exact names, and a bare CREATE INDEX would
-- abort the migration with 42P07 duplicate_table.
--
-- The definitions match what ensureChatTables() created (DESC on updated_at is
-- NULLS FIRST in Postgres), so a pre-existing index and a freshly created one
-- are identical.
--
-- This file is now immutable, like every applied migration. See lib/db/README.md.

CREATE INDEX IF NOT EXISTS "chat_messages_session_id_idx" ON "chat_messages" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "chat_sessions_employee_id_idx" ON "chat_sessions" USING btree ("employee_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "chat_sessions_updated_at_idx" ON "chat_sessions" USING btree ("updated_at" DESC NULLS FIRST);