-- schools.school_number: apply the constraint 0006 was credited with.
--
-- NOT a new decision. Migration 0006 made this column NOT NULL in July, and
-- the form validator has required it for longer. This exists because on
-- databases built with `push`, 0006's constraint was never actually applied
-- while the tracking table says it was.
--
-- The chain, since it took four files to see:
--
--   1. 0006 was hand-written, so `drizzle-kit generate` never ran for it and
--      no snapshot learned the constraint. All ten since say nullable.
--   2. The Drizzle declaration was never given .notNull() either — the same
--      omission, in the other file.
--   3. `push` applies the DECLARED schema, and the declaration said nullable.
--      So push-built databases got a nullable column.
--   4. backfill-drizzle-migrations-table.ts then marked 0006 applied so
--      `migrate` would stop colliding — which also means migrate can never
--      apply 0006's constraint there. Ever.
--
-- Exactly the failure that script's own header warns of: a migration marked
-- applied when it is not, the change skipped forever, the app booting happily
-- against a schema missing it.
--
-- This is a NEW tag, absent from that baseline, so migrate applies it normally.
--
-- NO DATA STATEMENT HERE, deliberately. Production had one school with no
-- number (NSA_IPES, 1 of 54; 0006 line 38 would have given it 315). The
-- tempting fix is an UPDATE in this file. That is against the rule in
-- README.md — schools are created and edited exclusively through the admin UI,
-- and nothing in startup or deploy code writes to that table. ensureSchools()
-- was removed for precisely this reason: it re-stamped every school on each
-- boot and reverted admin edits. A blank was filled in through the admin UI
-- instead, which is the supported path and leaves an audit trail.
--
-- IF THIS FAILS it is 23502, and it means that database still holds a school
-- with no number. Do not weaken this migration. Find them and give them their
-- numbers through the admin UI:
--     SELECT id, abbreviation, display_name FROM schools WHERE school_number IS NULL;

ALTER TABLE "schools" ALTER COLUMN "school_number" SET NOT NULL;
